// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "Application.h"
#include <stdlib.h>
#include <FL/Fl_Menu_Bar.H>
#include "EditorWindow.h"
#include "DisplayWindow.h"

class Gui {
public:
  Gui();
  Fl_Double_Window *MainWindow;
  Fl_Menu_Bar *menuBar;
  static Fl_Menu_Item menu_menuBar[];
  static Fl_Menu_Item *fileMenu;
  static Fl_Menu_Item *readFile;
private:
  inline void cb_readFile_i(Fl_Menu_*, void*);
  static void cb_readFile(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *writeFile;
private:
  inline void cb_writeFile_i(Fl_Menu_*, void*);
  static void cb_writeFile(Fl_Menu_*, void*);

public:
  static Fl_Menu_Item *ImageProcess;
  static Fl_Menu_Item *Update;
  static Fl_Menu_Item *AverageSmooth;
  static Fl_Menu_Item *MedianSmooth;
  static Fl_Menu_Item *GaussianSmooth;
  static Fl_Menu_Item *EdgeDetect;
  static Fl_Menu_Item *Undo;
  static Fl_Menu_Item *exitButton;
private:
  inline void cb_exitButton_i(Fl_Menu_*, void*);
  static void cb_exitButton(Fl_Menu_*, void*);

  // New callback functions for Image Processing menu items
  inline void cb_update_i(Fl_Menu_*, void*);
  static void cb_update(Fl_Menu_*, void*);

  inline void cb_averageSmooth_i(Fl_Menu_*, void*);
  static void cb_averageSmooth(Fl_Menu_*, void*);

  inline void cb_medianSmooth_i(Fl_Menu_*, void*);
  static void cb_medianSmooth(Fl_Menu_*, void*);

  inline void cb_gaussianSmooth_i(Fl_Menu_*, void*);
  static void cb_gaussianSmooth(Fl_Menu_*, void*);

  inline void cb_edgeDetect_i(Fl_Menu_*, void*);
  static void cb_edgeDetect(Fl_Menu_*, void*);

  inline void cb_undo_i(Fl_Menu_*, void*);
  static void cb_undo(Fl_Menu_*, void*);

public:
  CEditorWindow *EditorWindow;
  CDisplayWindow *DisplayWindow;
  void show();
  Application *app; 
};
#endif
